### ISSUE TITLE
Callback never called after start

### ISSUE THREAD

**Issue by gregorybolkenstijn** [tonyspiro/gulp-mamp#5]
The callback after start is never called:

```
gulp.task('start', function(cb){
    mamp(options, 'start', cb);
});
```

I have tasks running in sequence, waiting for the mamp start task to finish, but it never finishes.

**Comment by reneroth** [comment]
Same problem here, can we get a fix for this?

**Comment by tonyspiro** [comment]
Please open up a PR and I'll merge.
